name: py35
dependencies:
 - python=3.5.2=0
 - pip=8.1.1=py35_0
 - pip:
   - termcolor
   - python-magic==0.4.12
   - flask
   - typeguard
   - pygments
   - ansiconv
   - numpy
   - pillow
   - git+https://github.com/aflc/pyter@857a1552443f139a3
   - tensorflow
   - sphinx==1.5.1
